ianguage: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: thedanieljk-github
    token:
      secure: 07e13fa48d6f3c15d0f779f188909f21b2525b56
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
